export const questions = [
  "¿Qué es lo más embarazoso que tus padres te han pillado haciendo?",
  "¿Has sido cruel o malo con alguien en alguna ocasión?",
  "¿Qué cosa es la más extravagante que has hecho estando solo?",
  "¿Tienes algún miedo que no le hayas contado a nadie?",
  "¿Cuál es el mayor rechazo que has tenido en el amor?",
  "¿Hay algún secreto que no le hayas contado a tus padres?",
  "¿Cuál es la mentira más grande que has contado y no te han pillado?",
  "¿Te consideras una persona feliz?",
  "¿Qué es lo que más te gusta de tu persona? ",
  "¿Qué es lo que menos te gusta de tu persona? ",
  "Si pudieras borrar alguna experiencia negativa de tu vida, ¿cuál sería? ",
  "¿Qué es lo más loco que has hecho por amor? ",
  "¿Cuál es la última mentira que has contado? ",
  "¿Cuál es tu límite en las relaciones íntimas? ",
  "¿Qué cambiarías de tu vida si pudieras? ",
  "Si pudieras pedir un deseo ahora mismo, ¿cuál sería? ",
  "¿Te gustaría tener una experiencia íntima con alguien de tu mismo sexo? ",
  "¿Qué es lo que más te excita? ",
  "¿Has dado tu brazo a torcer? ",
  "¿Has utilizado algún objeto para fines sexuales a pesar de no ser ese su objetivo? ",
  "¿Tienes alguna fantasía sexual? ",
  "¿Le has roto el corazón a alguien alguna vez? ",
  "¿Me vas a llamar mañana? ",
  "¿Has hecho el amor en algún lugar prohibido? ",
  "¿Has sido infiel alguna vez? ",
  "¿Qué te satisface más? ",
  "¿Cuándo fue la última vez que mentiste? ",
  "¿Alguna vez has estado con alguien para olvidar a otra persona? ",
  "¿Tienes algún pretendiente ahora mismo? ",
  "¿Alguna vez has discutido con la pareja de un amigo? ",
  "¿Has jugado con los sentimientos de alguien alguna vez? ",
  "¿Te sientes solo? ",
  "¿Qué es lo más extravagante que has hecho? ",
  "¿Sueles abordar a las personas que te gustan, o te puede la timidez? ",
  "¿Cuánto tiempo duró la relación amorosa más breve que has tenido? ",
  "¿Has pensado alguna vez en tener algo con la madre de un amigo? ",
  "¿Tendrías un afer con alguno/a de tus primos/as? ",
  "¿Has tenido un encuentro íntimo con alguien a a quien hayas conocido ese mismo día? ",
  "¿Dejarías a tu pareja actual si a cambio ganaras un millón de dólares? ",
  "¿Has conocido alguna vez a alguien a quien le perdonarías todos los fallos? ",
  "¿Cuánto dinero ganas? ",
  "¿Cuánto dinero tienes ahorrado en el banco? ",
  "¿Crees que se puede viajar en el tiempo? ",
  "¿Has estado alguna vez detenido o en el calabozo? ",
  "¿Dormías con algún peluche cuando eras pequeño/a? ",
  "¿A qué partido político votas? ",
  "¿Eres feminista? ",
  "¿Alguna vez has tenido un accidente con el coche? ",
  "¿Te has vestido alguna vez con ropa de tu pareja? ",
  "¿Cuál es el disfraz más ridículo que has llevado? ",
  "¿Alguna vez has pensado en hacerte un tatuaje? ",
  "¿Te tatuarías el nombre de tu pareja? ",
  "¿Cuál es el momento en que has sentido más dolor físico en tu vida? ",
  "¿Con qué artista querrías pasar una noche loca? ",
  "Si tuvieras que elegir, ¿a quién salvarías de un incendio: a un hombre o a una familia de perros? ",
  "¿Qué es lo que te frustró no poder decirle ala última persona que te decepciono? ",
  "¿Si tuvieses que ocultar una de las partes de tu cuerpo que normalmente muestras públicamente, cuál sería? ",
  "¿Alguna vez has discriminado a alguien? ",
  "¿Qué característica física te haría no tener una cita con una persona? ",
  "¿Alguna vez has reprimido las ganas de robar algo? ",
  "¿Cuántos días seguidos has llegado a estar acostándote con alguien diferente cada día? ",
  "¿Harías un striptease? ",
  "¿Me dejas ver el historial de tu navegador de smartphone? ",
  "¿Te gustaría probar el BDSM? ",
  "¿Alguna vez te has enamorado de la pareja de un amigo?",
  "¿y de un familiar? ",
  "¿Te parece que estoy en buena forma? ",
  "¿Te has llegado a arrepentir de acostarte con alguien? ",
  "¿En qué aspectos crees que eres mejor que los demás? ",
  "¿Qué situaciones te hacen querer comportarte mal? ",
  "¿Qué es lo primero que pensaste al verme? ",
  "¿Qué es lo primero que pensaste al conocerme? ",
  "¿Has estado alguna vez con una pareja que fuera mucho más alta o mucho más bajita que tú?  ",
  "¿Qué opinas sobre el velo islámico?  ",
  "¿Estás contento/a con tu vida sexual? ",
  "¿Tienes alguna deuda con alguien?  ",
  "¿Qué es la última cosa que has buscado en Google?  ",
  "¿Cuál es tu youtuber favorito?  ",
  "¿Por qué crees que hay pobreza? ",
  "¿Has tenido algún trabajo que odiaras profundamente? ",
  "¿Qué cantante te da vergüenza reconocer que te gusta? ",
  "¿Hay alguna palabra secreta que sólo uséis con tus amigos? ",
  "¿Cómo fue tu peor experiencia sexual? ",
  "¿Te has enganchado alguna vez a alguna serie de TV muy mala?  ",
  "¿Cuál crees que es tu Cociente Intelectual independientemente de lo que digan los test? ",
  "¿Alguna vez has visto películas de contenido adulto con tu familia en otra habitación? ",
  "¿Qué opinas del capitalismo? ",
  "¿Cuántos años de trabajar sin parar crees que necesitarías para hacerte rico/a? ",
  "¿Con qué persona no te atreverías a debatir de política? ",
  "¿Crees que se debe poder votar de cualquier cosa? ",
  "¿Cuántas personas crees que te odian en el mundo? ",
  "¿Hay alguien que crea que eres muy poco inteligente? ",
  "¿Qué línea jamás cruzarías para conquistar a alguien? ",
  "¿Alguna vez has estado hasta muy tarde por la noche jugando a un videojuego? ",
  "¿Alguna vez has viajado a otra provincia solo para tener sexo? ",
  "¿Y a otro país? ",
  "¿En qué cosas crees que te admiran los demás? ",
  "¿Alguna vez te has arrepentido de no insultar a alguien? ",
  "¿Das importancia al dinero de tus potenciales parejas? ",
  "¿Cuánto tiempo estarías sin salir de una cama si te pagasen un dolar por cada minuto? ",
  "¿Hay algún/a deportista por el que darías todo por pasar una noche? ",
  "¿Has hecho algo ilegal en lo que llevamos de año? ",
  "¿Alguna vez se te ha caído una copa al suelo en un restaurante o discoteca? ",
  "¿Cuál es la habilidad que querrías poseer con todas tus fuerzas pero que nunca pudiste desarrollar? ",
  "Si fueses un dinosaurio, ¿cuál te gustaría ser? ",
  "¿Alguna vez te has sentido solo a pesar de tener gente alrededor? ",
  "¿Has escrito alguna vez un poema a alguien a quien querías? ",
  "¿Has causado algún desperfecto en la vía pública en alguna ocasión? ",
  "¿Eres de esas personas que solo pueden ir al lavabo en su casa? ",
  "¿Qué harías para protegerte de una invasión zombi? ",
  '¿Consideras que tu mascota es "uno más de la familia"? ',
  "¿Te gusta la pizza con piña? ",
  "¿Has probado alguna vez los caracoles? ",
  "¿Qué harías si mañana te tocase la lotería? ",
  "Cuando estás triste, ¿te pones música triste? ",
  "¿Has fantaseado con tener una noche loca con alguien de más de 50 años? ",
  "¿Tienes algún prejuicio sobre las gentes de alguna región de tu país? ",
  "¿Cuál es el regalo más feo que te han hecho? ",
  "¿Alguna vez estabas haciendo un trabajo de la universidad y lo has perdido todo y has tenido que empezarlo de cero? ",
  "¿Cuál es la vez en que has hecho más el ridículo? ",
  "¿Qué cualidad mía valoras más? ",
  "¿Cuál es la parte de tu cuerpo que menos te gusta? ",
  "Si fueras jefe de una multinacional, ¿serías un jefe estricto y exigente o más bien relajado y amigable? ",
  "De tu grupo de amigos, ¿quién es el más (o la más) irresponsable? ",
  "¿Quién es la persona que más necesitas en tu vida ahora mismo? ",
  "¿Consideras que tienes actitudes machistas? ",
  "¿Cuál fue el último libro que leíste? ",
  "¿Cuántas horas al día pasas navegando por internet? ",
  "¿Cuál es el regalo más incómodo que te ha dado un/a antiguo/a novio/a? ",
  "¿Cuál es el peor concierto al que has asistido? ",
  "¿Cuál es el deporte que se te da peor? ",
  "¿Alguna vez te has quedado sin gasolina? ¿Cómo resolviste la situación? ",
  "¿Quieres más a tu padre o a tu madre? ",
  "¿Te avergüenzas de algún gusto musical que tenías cuando eras adolescente? ",
  "¿Has conocido alguna vez a algún famoso? ¿Qué pasó? ",
  "¿Con el paso de los años, has cambiado de ideología? ",
  "¿Cuál es el peor antro al que has ido? ",
  "¿Has visto en alguna ocasión a una persona muerta? ",
  "Si pudieras elegir, ¿dónde irías a vivir? ",
  "¿Cuál es la asignatura que se te daba peor en la escuela? ",
  "¿Te has caído alguna vez por la calle? ",
  "¿Cuál es la pregunta incómoda que más detestas que te hagan? ",
  "¿Alguna vez has reciclado un regalo que te hicieron a ti para regalarlo tú a otra persona? ",
  "¿Prefieres tener medio millón de euros para gastar en 1 día o 300.000€ para gastar durante un mes? ",
  "Si te tocara la lotería, ¿informarías a tus amigos? ",
  "¿Alguien de tu familia tiene algún trastorno mental? ",
  "¿Has roto algún mueble en alguna ocasión por ir borracho? ",
  "¿Cuál era tu cómic favorito cuando eras niño/a? ",
  "¿Si pudieras elegir una cualidad de entre estas tres, cuál te quedarías? Ser alto, ser guapo o ser exito",
  "¿Has comido alguna vez algo que te hiciera vomitar (o casi)? ",
  "¿Te has acostado alguna vez con alguien por un motivo que no fuera ni amor ni atracción? ",
  "¿Qué personaje público consideras un mito erótico? ",
  "¿Qué es más importante en tu vida: tu vida personal o tu carrera profesional? ",
  "¿Sabes imitar la voz de algún famoso? ",
  'Termina la frase: "No podría vivir en una casa que no tuviera..." ',
  "¿Quién de tu grupo de amigos consideras que es menos confiable? ",
  "¿Hasta qué edad te gustaría vivir? ",
  "¿Crees en el derecho a llevar armas? ",
  "¿A qué tipo de personas crees que jamás podrías seducir? ",
  "¿Cuál es el talento que te frustra más no tener? ",
  "¿Qué es lo más asqueroso que te ha pasado? ",
  "¿A cuántos de tus amigos entregarías a la policía su supieses que han estado comentiendo crímenes? ",
  "¿Alguna vez has consumido drogas solo para intentar flirtear con alguien? ",
  "¿Alguna vez has intentado obtener mejores calificaciones haciendo trampas? ",
  "¿Crees que hay áreas de conocimiento que jamás serías capaz de aprender? ",
  "¿Te han rechazado un beso alguna vez? ",
  "¿Has mentido alguna vez para ligar? ",
  "¿Cuál es tu definición de “amor”? ",
  "¿Has encontrado a alguien manteniendo relaciones sexuales? ",
  "¿Crees en dios? ",
  "¿Has tenido alguna pareja mucho mayor o más joven que tú? ",
  "¿Qué opinión tienes sobre la eutanasia? ",
  "¿Te gustaría ser millonario? ",
  "¿Qué opinión tienes sobre el gobierno? ",
  "¿Qué opinas sobre el comunismo? ",
  "¿Saldrías con una actriz porno? ",
  "¿A qué edad perdiste la virginidad? ",
  "¿Qué es lo peor que has hecho para acostarte con alguien? ",
  "¿Cuál es el peor insulto que has dedicado a alguien? ",
  "¿Te has peleado alguna vez? ",
  "¿Qué opinas del rey? ",
  "¿Hasta qué edad te orinaste en la cama? ",
  "¿Qué opinión tienes de la policía? ",
  "¿Qué opinas de los judíos? ",
  "¿Qué opinas de los asiáticos? ",
  "¿Si volvieses a nacer, repetirás tu vida de la misma manera? ",
  "¿Si pudieses elegir, en qué país te gustaría nacer? ",
  "¿Crees que los pobres no se esfuerzan lo suficiente? ",
  "¿Qué opinas de la infidelidad? ",
  "¿Qué opinas del matrimonio? ",
  "¿Qué opinas de la Iglesia? ",
  "¿Qué opinas del aborto? ",
  "¿Crees que todas las razas son igual de inteligentes? ",
  "¿Qué opinas sobre la prostitución? ",
  "¿Qué opinas sobre la cadena perpetua? ",
  "¿Qué opinas sobre la inmigración? ",
  "¿Crees que todo el mundo debería poder votar? ",
  "¿Qué opinión te merecen los homosexuales? ",
  "¿Qué opinas de Jeff Bezos? ",
  "¿Qué opinión te merecen las políticas de identidad? ",
  "¿Cuál es la comida que no puedes ni oler? ",
  "¿Vivirías aislado en una cabaña durante 1 mes a cambio de 15.000€? ",
  "Si solo pudieras comer un alimento por el resto de tu vida, ¿cuál sería? ",
  "¿Cuál es la leyenda urbana que más tiempo has creído que era verdadera? ",
  "¿Qué opinas de la nueva ley en España que hace que una persona pueda cambiar su sexo sin necesidad de pasar por pruebas médicas o psicológicas? ",
  "¿Qué medio de transporte soportarías mejor en un viaje largo? ",
  "¿Alguna vez has descargado alguna película para adultos en tu ordenador? ",
  "¿Tienes alguna canción que te encanta a pesar de que los demás suelen considerarla una canción cutre? ",
  "¿Alguna vez se te ha roto un teléfono móvil de forma graciosa o absurda? ",
  "¿Alguna vez te han cacheado? ",
  "Si pudieras escoger bañarte en una piscina llena de un líquido diferente al agua, ¿qué líquido pedirías? ",
  "Si fueras testigo de una pelea en la calle, ¿serías capaz de intentar mediar o pasarías de largo? ",
  "¿Qué opinas de la piratería de música y películas? ",
  "¿Qué fruta no soportas? ",
  "¿En qué situación temiste más por tu vida? ",
  "¿Cuál es tu dibujo animado favorito? ",
  "¿Has vomitado alguna vez en algún sitio público? ",
  "¿A qué ciudad nunca irías a vivir? ",
  "¿Qué es lo que más te molesta de mí? ",
  "¿De qué color nunca irías vestido a una boda? ",
  "¿Cuál es el famoso que más te ilusionaría encontrarte por la calle? ",
  "¿Cuál es la apuesta más loca que has hecho en tu vida? ",
  "¿Qué cosa quisiste aprender pero nunca lo lograste? ",
  "¿Te has caído alguna vez cuando mucha gente te estaba mirando? ",
  "¿Cuál es el trabajo que no harías ni aunque te pagaran un sueldo increíble? ",
  "¿Alguna vez has salido de casa sin ropa interior o sin bañador? ",
  "¿Qué juego basado en la agilidad mental se te da peor? ",
  "¿Cuál fue la vez en la que fuiste más cruel con alguien que te estaba ofreciendo un servicio? ",
  "¿Cuál es la persona más famosa con la que has intentado hablar por Internet? ",
  "¿Qué es lo más vergonzoso que has enviado en el último mes por el sistema de mensajería que más usas en tu móvil? ",
  "¿Qué parte de tu cuerpo crees que ha envejecido o madurado menos que el resto? ",
  "¿Cuál fue la vez en la que más quedaste en evidencia al creer que sabías lo suficiente acerca de un tema? ",
  "¿En alguna ocasión alguien intentó flirtear descaradamente contigo y tú no te diste cuenta? ",
  "¿Cuál es la creencia religiosa que consideras más absurda a pesar de estar muy extendida? ",
  "¿En algún momento has llegado a creer que estabas viviendo una experiencia paranormal? ",
  "¿Alguna vez has amenazado a alguien? ",
  "¿Te has tirado un pedo en público alguna vez y te han pillado? ",
  "¿Cuál es la vez que más tiempo has estado sin ducharte? ",
  "¿Tienes miedo a algo? ",
  "¿Alguna vez te has caído yendo en bicicleta? ",
  "¿Cuál fue tu experiencia laboral más desastrosa? ",
  "¿Cuál es la comida que más te ha disgustado probar? ",
  "¿Alguna vez se te ha caído el móvil al retrete? ",
  "¿Te has saltado un semáforo en rojo en alguna ocasión? ",
  "¿Qué es lo que más te gustaría tener en la vida y aún no tienes? ",
  "¿Cuál fue tu sueño sexual más tórrido? ",
  "¿Has soñado con algún amigo/amiga? ",
  "¿Te han roto el corazón alguna vez? ",
  "¿Has hecho el amor en un avión? ",
  "¿Qué harías si fueras invisible? ",
  "¿Si pudieras viajar a cualquier parte del mundo, dónde irías? ",
  "¿Tienes algún piercing? ",
  "¿Has estado involucrado en alguna pelea? ",
  "¿Has tenido relaciones sexuales en un cine? ",
  "¿Cuál fue tu peor borrachera? ",
  "¿Si anduvieses desnudo por la calle te taparías la cara o los genitales? ",
  "¿Me dejas ver tus chats de Whatsapp? ",
  "¿Alguna vez te enamoraste de tu profesor? ",
  "¿Qué edad tenía la persona de mayor edad con la que te has acostado? ",
  "¿Qué edad tenía la persona de menor edad con la que te has acostado? ",
  "¿Cuál fue tu peor cita? ",
  "¿Cuál fue tu mejor cita? ",
  "¿Qué opinas sobre el anarquismo? ",
  "¿Crees que hombres y mujeres pueden ser amigos? ",
  "¿Cómo te gustan los hombres/las mujeres? ",
  "¿De qué equipo de fútbol eres? ",
  "¿Qué opinas sobre el estado de Israel? ",
  "¿Alguna vez te has pegado en una discoteca o en un bar? ",
  "¿Cómo fue tu primera experiencia sexual? ",
  "¿Has probado los insectos? ",
  "¿Has probado la comida de perro? ",
  "¿De todos tus amigos, cuál es el que más bebe? ",
  "¿Has sufrido algún coma etílico? ",
  "¿Cuál fue tu primer mito erótico? ",
  "¿Crees en el demonio? ",
  "¿Has rechazado un beso alguna vez? ",
  "¿Qué opinas de Estados Unidos? ",
  "¿Qué opinas de Donald Trump? ",
  "¿Qué opinas de Vladimir Putin? ",
  "¿Qué opinas de los negros? ",
  "¿Qué opinas de Michael Jackson? ",
  "¿Qué opinas de Bill Gates? ",
  "¿Quieres casarte? ",
  "¿Qué opinas del presidente de tu país? ",
  "¿Crees en los extraterrestre",
]

export const randomNumber = ( max: number ): number => {
  return Math.round( ( max - 0 ) * ( Math.random() + 0 ) )
}
